### ISSUE TITLE
Rename all interfaces consistently

### ISSUE THREAD

**Issue by mpsijm** [thervh70/ContextProject_RDD#93]
Open for voting: 
:+1: for naming all interfaces with an `I` prefix (like `ISemanticEvent` or `IDatabaseAdaptable`)
:-1: for naming all interface without any prefix (like `SemanticEvent` or `DatabaseAdaptable`)
Any other suggestions? Leave them in the comments :)

**Comment by Exclaminator** [comment]
I think the prefix is unnecessary since the different implementations all have something defining about them. This defining part / vs the abstract prevents name collision. Semantics are rather useless in this context, since a class implementing something will properly refer to what the interface is, and accepting an object of either a class or interface is an unnecessary place for discrimination due to the open/closed principle.
